### ISSUE TITLE
WARNING! to all Tutorial students! THIS THING COSTS

### ISSUE THREAD

**Issue by marksteven** [awslabs/aws-amplify-unicorntrivia-workshop#76]
I reformed this tutorial last week and it all went well.
Until I went to AWS billing to see what it cost.
I did a 10-15 test DEV stream using the setup described here and it cost me
US$670 dollars!

So be warned this is not a cheap service in fact it is off the scale on cost and would recommend to anyone to look elsewhere.

**Comment by smp** [comment]
Hi mark, thanks for the feedback.

- Was there a specific reason you created 15 separate streams?
- Do you have any ideas on how we could help others avoid un-necessary costs?

For what it's worth, we have a new workshop based on the Amazon Interactive Video Service (IVS) that will likely end up being cheaper for most, you can find it here http://unicornlive.workshop.aws/

We're also tracking [a ticket](https://github.com/awslabs/amplify-video/issues/9) within Amplify Video that would support single-pipeline mode in MediaLive and further reduce costs for the AWS Elemental Services used by Amplify Video.

**Comment by marksteven** [comment]
Hi SMP for getting back to me.
As far as I am aware I followed the tutorial exactly and it is new to me now that I spun up 15 separate streams as I was simply following instructions. Only clue I can think of was the step from memory of something about allowing different device streams for viewers? So can only assume from this a series of different sized streams was set up. As this is a Dev environment thing it should be able to be set up in only one regional and really only needs one single stream.
Anything over that should have a waring label on it. And I think an emphasis right at the start to delete the whole project quickly after getting it going or incur costs. In this regard there should be a way to set up a service ready to spool up when you need it but not cost so all steps can be done quickly. Maybe there already is a way but as a beginner I have not been able to find this yet.  I will defiantly look into the link you provided and see how that goes. A single pipe I would defiantly be interested in. Again IF the costs add up

**Comment by agomez2** [comment]
I was just charged $1,754 for the Elemental MediaLive usage. 

I did not know I had to stop it.

Thanks Amazon

**Comment by marksteven** [comment]
Get on to billing they helped me out, but yes it is a big pain as they do NOT tell you you are going to get nailed.
From painful history go check in ALL other aws territories for any auto deploys NOW (clock is ticking) and delete the lot

**Comment by wizage** [comment]
Hello @agomez2,

Sorry to hear that, please open a support case with billing immediately and they can help you out. We are working on a cheaper workshop with a new service call Amazon Interactive Video Service (IVS). Please also make sure you do the clean up section provided in this workshop: https://github.com/awslabs/aws-amplify-unicorntrivia-workshop/blob/master/documentation/wrap_up_doc.md 

This clean up is key and very important. The Elemental media services will keep working even if you are not streaming to them (sort of like EC2) so it is important to turn things off when they aren't being used. The new service IVS has auto shut off features which is why we are building a new workshop around that.

**Comment by agomez2** [comment]
Thanks both,

The first thing I did was close the account. 

After that I sent a message to billing support but they have not answered since I did. Hopefully they will answer on Monday.

I think AWS should offer a "tutorial" type of account or some other solution to this kind of things.

The experience is quite bad to be honest.

I had even set up budgets because I had seen the message from Mark Steven but it seems they did not work.

Thanks.
